/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const incidents_Logic = require('./code/incidents-logic');

class demouser01Srv extends LCAPApplicationService {
    async init() {

        this.before('UPDATE', 'Incidents', async (request) => {
            await incidents_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    demouser01Srv
};